<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Principal</title>
  <link href="/css/home.css" rel="stylesheet">
  <link href="/css/minibootstrap.css" rel="stylesheet">
</head>
<body>
  <main class="container">
      <h1 class="my-4 text-center text-lg-left">
      <?php //strtoupper(str_replace("_", " ", $dato));?>
      </h1>
      <div class="row text-center text-lg-left">
        <?php foreach ($data as $artista) { ?>
        <div class="col-sm-12 col-md-6 col-lg-3">
        <a href="autor.php?id_autor=<?php echo str_replace(" ", "_", $artista['nombre']);?>" class="d-block mb-4 h-100">
        <img class="embed-responsive-item" control
        src="../../img/img_artista/artistas/<?php echo str_replace(" ", "_", $artista['nombre']);?>.png"/>
        </a>
        </div>
       <?php } ?>
      </div>
  </main>
</body>
</html>
