<?php 
session_start();
$_SESSION['usuario'] = 1;
/*
if(isset($_SESSION['logeado'])){
  $_SESSION['logeado'] == true;
}else{
  header('refresh:1,../index.php');
  die();
}
*/
?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Principal</title>
  <link href="../../css/principal.css" rel="stylesheet">
</head>
<body>
  <header>
    <div>
      <div>
        <span>
          <img src="../../img/logoNuevo.png">
        </span>
      </div>
      <div>
        <input type="text" onkeypress= "if(event.keyCode == 13) cambiarIframe4()"  placeholder="Buscar..." autofocus />
      </div>
      <div>
        <span>
          <img src="../../img/usu.png">
        </span>
      </div>
      <div>
        <span>
          <a href="../../index.php?redirigido=cierreSesion"> <img src="../../img/cerrarSesion.jpeg"></a>
        </span>
      </div>
    </div>  
  </header>
  <main class="container">
    <iframe id="iframe" src="/usuario/home"></iframe>
  </main>
  <footer>    
    <div>
      <button type="button" id="biblioteca">
        <a href="biblioteca.html">
          <img src="../../img/imgReproductor/library.png">
        </a>
      </button>
      <audio controls >
        <source src="../../public/musica/cancion1.mp3" type="audio/ogg">
      </audio> 
    </div>
  </footer>
</body>
 <script src="../../js/principal.js"></script>
</html>
