
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Principal</title>
  <link href="/css/principal.css" rel="stylesheet">
</head>
<body>
  <header>
    <div>
      <div>
        <span>
          <img src="/img/logoNuevo.png">
        </span>
      </div>
      <div>
        <input type="text" onkeypress= "if(event.keyCode == 13) cambiarIframe4()"  placeholder="Buscar..." autofocus />
      </div>
      <div>
        <span>
          <img src="/img/usu.png">
        </span>
      </div>
      <div>
        <span>
          <a href="/usuario/salir"> <img src="../../img/cerrarSesion.jpeg"></a>
        </span>
      </div>
    </div>  
  </header>
  <main class="container">
    <iframe id="iframe" src="/usuario/home"></iframe>
  </main>
  <footer>    
    <div>
      <button type="button" id="biblioteca">
        <a href=" ">
          <img src="/img/imgReproductor/library.png">
        </a>
      </button>
  
      <audio controls onended="cambiarCancion()" id="audioControl">
        <source src="" type="audio/mp3" id="audio">
      </audio> 
    </div>
  </footer>
</body>
<script>
          let lista = [
          <?php 
         
          $nombreCancion= "";
          $nombreAutor;
          foreach($data['lista'] as $clave => $valor){
             
            foreach($data['lista'][$clave] as $key => $value){
                if($key == 'nombre_cancion'){
                  $nombreCancion = str_replace(" ","_",$value);
                }
                if($key == 'nombre_autor'){
                  $nombreAutor = str_replace(" ","_",$value);
                }
                
            }
          $rutaCancion = "/musica/".$nombreAutor."/".$nombreCancion.".mp3";
          
            echo '"'.$rutaCancion.'"';
            echo ",";
            
          }     
           
          
          ?>
           
        
          ];
         // palabrasJuego.push(palabrasJuego.shift())
         let contador= 0;
          let control = document.getElementById('audioControl');
          control.src = lista[contador];
          control.load();

          
          function cambiarCancion(){
            contador++;
            control.src = lista[contador];
            control.load();
            control.play();
            if(contador == lista.length){
              contador = 0;
            }
          
          
          }
          
       

          alert(lista[0]);
        </script>
 <script src="/js/principal.js"></script>
</html>
