
	<!DOCTYPE html>	
	<html lang="es">
	<head>
	<meta charset="UTF-8">
	
	<link rel="stylesheet" type="text/css" href="/css/registrate.css">
	<title>Registrate</title>
	<style>
		form{
		
			display:flex;
			flex-direction:column;
		}
		input{
			width:250px;
			margin-top:10px;
		}
		input[type="submit"]{
			margin-top:40px;
			margin-right:70px;
			width:120px;
		}

		a{
			text-decoration:none;
			color:white;
		}
		label{
			margin-top:10px;
			color:white;
		}

		label:first-of-type{
			margin-left:px;
		}

		input:first-of-type{
			margin-left:50px;
		}

		input[type="email"]{
			margin-left:50px;
			
		}

	</style>
	</head>
	<body>
    <div class="contenedor">
		<div class="tarjeta">
			<div class="cabecera">
				<h3>Regístrate</h3>
			</div>
				
					
					<div class="grupo">
					       <?=$data['form']?>
					</div>
					<div>				
					
					
			<a href="/usuario/login" id="enlace">Volver a Login</a>	
		</div>
	</body>
	</html>
