
	<!DOCTYPE html>	
	<html lang="es">
	<head>
	<meta charset="UTF-8">
	
	<link rel="stylesheet" type="text/css" href="/css/registrate.css">
	<title>Registrate</title>
	</head>
	<body>
    <div class="contenedor">
		<div class="tarjeta">
			<div class="cabecera">
				<h3>Regístrate</h3>
			</div>
				<form action="#" method="POST" class="formulario">
					
					<div class="grupo">
					       <?=$data['form']?>
					</div>					
					
					
				</form>
		</div>
	</body>
	</html>
