<?php 
echo "<pre>";
//print_r($data);
echo"</pre>";
?>
<head>
  <!--<link href="/css/artista.css" rel="stylesheet">-->
  <?=$data['css']?>
  
</head>
<body>
  <main class="container">
    <div id="nombreArtista">
        <?php echo strtoupper($data['autor'][0]['nombre_autor']);?>
    </div>
    <div id="datosArtista">
        <div class="col-12 col-md-6">
            <img src="/img/img_artista/artistas/<?= str_replace(" ", "_", $data['autor'][0]['nombre_autor']);?>.png">
        </div>
        <div class="col-12 col-md-6">
            <?= $data['autor'][0]['informacion'];?>
        </div>
    </div>
    <div class="discos">
        <?php foreach($data['discos'] as $claveDisco => $valorDisco){ ?>
            <table class="col-">
                <caption>
                    <?= strtoupper($valorDisco['nombre_disco']); ?>
                </caption>
                    <?php 
                        foreach($data['canciones'] as $clave => $valor){ 
                            if($valorDisco['id_disco'] == $valor['id_disco']){ ?>
                                <tr>
                                    <td>
                                        <?= strtoupper( $valor['nombre_cancion']); ?>
                                    </td>
                                    <td>
                                        <button type="button">
                                            <img src="/img/img_artista/mas.png"id="img">
                                        </button>
                                    </td>
                                </tr>
                      <?php }
                        }
        } ?>
            </table>
    </div>
  </main>
</body>

