<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Principal</title>
  <link href="/css/artista.css" rel="stylesheet">
  <link href="/css/minibootstrap.css" rel="stylesheet">
</head>
<body>
  <main class="container">
    <div id="nombreArtista">
        <?php echo strtoupper($data['autor'][0]['nombre']);?>
    </div>
    <div id="datosArtista">
        <div class="col-12 col-md-6">
            <img src="/img/img_artista/artistas/<?= str_replace(" ", "_", $data['autor'][0]['nombre']);?>.png">
        </div>
        <div class="col-12 col-md-6">
            <?= $data['autor'][0]['informacion'];?>
        </div>
    </div>
    <div class="discos">
        <?php foreach($data['discos'] as $claveDisco => $valorDisco){ ?>
            <table class="col-">
                <caption>
                    <?= strtoupper($valorDisco['nombre']); ?>
                </caption>
                    <?php 
                        foreach($data['canciones'] as $clave => $valor){ 
                            if($valorDisco['id_disco'] == $valor['id_disco']){ ?>
                                <tr>
                                    <td>
                                        <?= strtoupper( $valor['nombre'])."nombre<br>"; ?>
                                    </td>
                                    <td>
                                        <button type="button">
                                            <img src="/img/img_artista/mas.png">
                                        </button>
                                    </td>
                                </tr>
                      <?php }
                        }
        } ?>
            </table>
    </div>
  </main>
</body>
</html>
