 <?=$data['css']?>
 
  <style>
      caption{color:whitesmoke;}

      a{
          padding-left:20px;
          font-size:2.8em;
          text-decoration:none;
          color:grey;
      }
     
      tr:first-of-type{
          border-bottom:6px groove black;
          padding:5px;
          text-transform:uppercase;
          background-color:#004275;
          color:whitesmoke;
      }

  </style>

<body>
  <main class="container">
    <div id="nombreArtista">
        <?php echo strtoupper($data['autor'][0]['nombre_autor']);?>
    </div>
    <div id="datosArtista">
        <div class="col-12 col-md-6">
            <img src="/img/img_artista/artistas/<?= str_replace(" ", "_", $data['autor'][0]['nombre_autor']);?>.png">
        </div>
        <div class="col-12 col-md-6">
            <?= $data['autor'][0]['informacion'];?>
        </div>
    </div>
    <div class="discos">
        <?php foreach($data['discos'] as $claveDisco => $valorDisco){ ?>
            <table class="col-">
                <caption>
                    <?= strtoupper($valorDisco['nombre_disco']); ?>
                </caption>
               
                    <tr>
                        <th>Nombre</th><th>Añadir Cancion</th>
                    </tr>
                
                    <?php 
                        foreach($data['canciones'] as $clave => $valor){ 
                            if($valorDisco['id_disco'] == $valor['id_disco']){ ?>
                                <tr>
                                    <td>
                                        <?= strtoupper( $valor['nombre_cancion']); ?>
                                    </td>
                                    <td>                                           
                                       <a href="/usuario/addCancion/<?=$valor['nombre_cancion']?>" > <i class="fas fa-folder-plus"></i></a>                 
                                    </td>
                                </tr>
                      <?php }
                        }
        } ?>
            </table>
    </div>
  </main>
</body>

